# -*- coding: utf-8 -*-
"""把 src/ 下的 Python 源码同步进 DataBackupFTPServer.bat 的内嵌块。

背景：bat 版是「零依赖、可审阅」的路线——它自己带一份服务端代码（运行时从自身尾部
提取到 %TEMP% 执行），所以源码与 bat 内嵌副本是两份。历史上靠手工同步，容易漏改。

用法（改完 src/*.py 后跑一次即可）：
    python tools/sync_bat.py           # 同步并自检
    python tools/sync_bat.py --check   # 只检查是否已同步（不写文件，CI 可用）

内嵌格式：
    ###FILE:ftp_core.py###       ← 到下一个 marker 之前
    ###FILE:ftp_server.py###     ← 到文件末尾
bat 里用 PowerShell 按这两个 marker 的行号切片提取，逻辑与下面 verify() 一致。
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COMPANION_DIR = os.path.dirname(HERE)
SRC_DIR = os.path.join(COMPANION_DIR, "src")
BAT_PATH = os.path.join(COMPANION_DIR, "DataBackupFTPServer.bat")

# (src 下的文件名, 提取到 %TEMP% 后的文件名)；ftp_server.py 必须最后（bat 切到文件末尾）
EMBED_FILES = (
    ("ftp_core.py", "ftp_core.py"),
    ("DataBackupFTPServer.py", "ftp_server.py"),
)
MARKER_HEAD = "###FILE:%s###"


LAUNCHER = r"""@echo off
chcp 65001 >nul
setlocal EnableExtensions EnableDelayedExpansion
set "SCRIPT_VER=2.0"
title DataBackup Companion - FTP Backup Server v2.0 (GUI)

REM ============================================================
REM  DataBackup Companion - FTP Backup Server (Windows, GUI)
REM
REM  Original idea by Coolapk user @miaocuijiao12448
REM    https://www.coolapk.com/feed/73346386
REM  Maintained by boluo4169-commits (DataBackup custom)
REM    https://github.com/boluo4169-commits/Android-DataBackup-custom
REM  License: MIT
REM
REM  This .bat is a self-contained launcher (no exe, no install):
REM    1. Auto request admin rights (UAC) - needed for firewall rules
REM    2. Locate or auto-install Python, install pyftpdlib if missing
REM    3. Open the firewall ports (2121 + passive 60000-60100)
REM    4. Extract the embedded Python sources and launch the GUI
REM       (fill in account / password / folder, then click Start)
REM
REM  Usage:
REM    Double-click to launch the GUI (no prompts, everything in the window)
REM    CLI: this.bat <username> <password> <backup_dir>   (prefills the GUI)
REM    Diagnose: this.bat --diagnose [backup_dir]         (no GUI, no admin)
REM
REM  MAINTAINERS: the embedded sources at the bottom are generated by
REM    tools/sync_bat.py - never edit them by hand.
REM ============================================================

REM ---------- request admin rights (firewall rules need them) ----------
REM Diagnose mode: skip UAC (admin not needed for --diagnose)
if /i "%~1"=="--diagnose" goto :admin_ok
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo 正在请求管理员权限...
    powershell -NoProfile -Command "$a=@(); if('%~1' -ne ''){$a+='%~1'}; if('%~2' -ne ''){$a+='%~2'}; if('%~3' -ne ''){$a+='%~3'}; Start-Process -FilePath '%~f0' -ArgumentList $a -Verb RunAs"
    exit /b
)
:admin_ok

echo.
echo   DataBackup Companion - FTP 数据服务器 (GUI)  v%SCRIPT_VER%
echo   ------------------------------------------------------
echo   原始创意 : 酷安 @喵脆角12448
echo   重构维护 : boluo4169-commits (酷安 @骏冲冲)
echo   项目地址 : https://github.com/boluo4169-commits/Android-DataBackup-custom
echo   许可     : MIT
echo.

REM ---------- port pre-check (informational only) ----------
netstat -ano | findstr ":2121" >nul 2>&1
if %errorlevel% equ 0 echo [提示] 端口 2121 可能已被占用, 若启动失败请改端口或关闭占用程序。

REM ---------- locate Python, install if missing ----------
REM Prefer the official launcher (py -3) and standard install paths over bare
REM "python": in some environments PATH's python is a venv/conda shim without
REM pip or pyftpdlib, which would be misreported as "install failed".
set "PYEXE="
if exist "%LOCALAPPDATA%\Programs\Python\Python312\python.exe" set "PYEXE=%LOCALAPPDATA%\Programs\Python\Python312\python.exe"
if not defined PYEXE if exist "%LOCALAPPDATA%\Programs\Python\Python313\python.exe" set "PYEXE=%LOCALAPPDATA%\Programs\Python\Python313\python.exe"
if not defined PYEXE if exist "%LOCALAPPDATA%\Programs\Python\Python311\python.exe" set "PYEXE=%LOCALAPPDATA%\Programs\Python\Python311\python.exe"
if not defined PYEXE (where py >nul 2>&1 && set "PYEXE=py -3")
if not defined PYEXE (where python >nul 2>&1 && set "PYEXE=python")
if defined PYEXE (%PYEXE% -c "import sys" >nul 2>&1 && goto :python_ok)
set "PYEXE="
echo 未检测到 Python, 正在自动安装 Python 3.12, 请稍候...
winget install --id Python.Python.3.12 -e --silent --scope user --accept-package-agreements --accept-source-agreements --disable-interactivity
if exist "%LOCALAPPDATA%\Programs\Python\Python312\python.exe" set "PYEXE=%LOCALAPPDATA%\Programs\Python\Python312\python.exe"
if not defined PYEXE (where py >nul 2>&1 && set "PYEXE=py -3")
if not defined PYEXE (where python >nul 2>&1 && set "PYEXE=python")
if defined PYEXE (%PYEXE% -c "import sys" >nul 2>&1 && goto :python_ok)
echo [错误] Python 仍然不可用, 请手动安装后重新运行脚本:
echo         winget install --id Python.Python.3.12 -e
pause
exit /b 1
:python_ok
echo Python 路径: %PYEXE%

REM ---------- ensure pyftpdlib is installed ----------
:ensure_ftpdep
%PYEXE% -c "import pyftpdlib" >nul 2>&1
if not errorlevel 1 goto :ftpdep_ok
echo 正在使用国内镜像源安装 pyftpdlib...
%PYEXE% -m pip install pyftpdlib -i https://pypi.tuna.tsinghua.edu.cn/simple --disable-pip-version-check -q
%PYEXE% -c "import pyftpdlib" >nul 2>&1
if not errorlevel 1 goto :ftpdep_ok
echo 国内镜像失败, 尝试官方 PyPI 源...
%PYEXE% -m pip install pyftpdlib --disable-pip-version-check -q
%PYEXE% -c "import pyftpdlib" >nul 2>&1
if not errorlevel 1 goto :ftpdep_ok
echo 尝试用户目录安装...
%PYEXE% -m pip install pyftpdlib --user -i https://pypi.tuna.tsinghua.edu.cn/simple --disable-pip-version-check -q
%PYEXE% -c "import pyftpdlib" >nul 2>&1
if not errorlevel 1 goto :ftpdep_ok
REM Current interpreter really can not install it (e.g. a venv python with no pip).
REM Fall back to the official launcher once, then give up.
if defined FTPDEP_RETRIED goto :ftpdep_fail
if /i "%PYEXE%"=="py -3" goto :ftpdep_fail
where py >nul 2>&1
if errorlevel 1 goto :ftpdep_fail
set "PYEXE=py -3"
set "FTPDEP_RETRIED=1"
echo 当前解释器无法安装依赖, 换用官方 launcher (py -3) 重试...
goto :ensure_ftpdep
:ftpdep_fail
echo [错误] pyftpdlib 安装失败, 请手动执行:
echo         %PYEXE% -m pip install pyftpdlib -i https://pypi.tuna.tsinghua.edu.cn/simple
pause
exit /b 1
:ftpdep_ok
echo pyftpdlib: OK

REM ---------- firewall rules (2121 + passive 60000-60100); diagnose mode skips ----------
if /i "%~1"=="--diagnose" (
    echo 诊断模式: 跳过防火墙配置
) else (
    netsh advfirewall firewall show rule name="DataBackup FTP 2121" >nul 2>&1
    if errorlevel 1 netsh advfirewall firewall add rule name="DataBackup FTP 2121" dir=in action=allow protocol=TCP localport=2121
    netsh advfirewall firewall show rule name="DataBackup FTP Passive 60000-60100" >nul 2>&1
    if errorlevel 1 netsh advfirewall firewall add rule name="DataBackup FTP Passive 60000-60100" dir=in action=allow protocol=TCP localport=60000-60100
    echo 防火墙规则: 已就绪
)

REM ---------- extract the embedded python sources (ftp_core.py + ftp_server.py) ----------
set "WKDIR=%TEMP%\DataBackupFTP_server"
if not exist "%WKDIR%" mkdir "%WKDIR%"
powershell -NoProfile -Command "$l=Get-Content -LiteralPath '%~f0' -Encoding UTF8; $a=($l|Select-String '^###FILE:ftp_core.py###$').LineNumber; $b=($l|Select-String '^###FILE:ftp_server.py###$').LineNumber; if(-not $a -or -not $b){Write-Error 'FILE markers not found'; exit 1}; [IO.File]::WriteAllLines('%WKDIR%\ftp_core.py', $l[$a..($b-2)]); [IO.File]::WriteAllLines('%WKDIR%\ftp_server.py', $l[$b..($l.Count-1)])"
if errorlevel 1 (
    echo [错误] 内嵌服务端代码提取失败
    pause
    exit /b 1
)

REM ---------- security notice ----------
echo.
echo **********************************************************************
echo   注意: FTP 为明文协议, 请仅在可信的家庭/办公局域网内使用,
echo         不要将端口暴露到公网。传输完成后可直接关闭本窗口。
echo **********************************************************************

REM ---------- launch ----------
set "PYTHONIOENCODING=utf-8"

REM Diagnose mode: keep the console (the report is printed here). No pause so it
REM can also be driven non-interactively (scripts / CI).
if /i "%~1"=="--diagnose" (
    echo 正在生成诊断包...
    %PYEXE% -X utf8 -u "%WKDIR%\ftp_server.py" %*
    echo.
    echo 诊断包已生成, 可以关闭本窗口
    exit /b
)

REM GUI mode: hand off to a windowed interpreter (pythonw / pyw) and let this
REM console exit, so the user only sees the GUI window. Startup errors are
REM reported by the GUI itself; anything that must be seen here (Python /
REM pyftpdlib install failures) already happened above.
call :pick_windowed
echo 正在启动图形界面, 填好账号密码与目录后点「开启」...
start "" %PYWEXE% -X utf8 "%WKDIR%\ftp_server.py" %*
exit /b

:pick_windowed
REM Derive the windowed twin of %PYEXE% (python.exe -> pythonw.exe, py -3 -> pyw -3).
set "PYWEXE="
if /i "%PYEXE%"=="py -3" set "PYWEXE=pyw -3"
if /i "%PYEXE%"=="py" set "PYWEXE=pyw"
if /i "%PYEXE%"=="python" set "PYWEXE=pythonw"
if not defined PYWEXE set "PYWEXE=%PYEXE:python.exe=pythonw.exe%"
REM Check it exists instead of probing it: pyw / pythonw detach immediately, so
REM running them gives no reliable errorlevel. Fall back to the console one when
REM the windowed twin is missing.
set "PYWOK="
if /i "%PYWEXE%"=="pyw -3" (where pyw >nul 2>&1 && set "PYWOK=1")
if /i "%PYWEXE%"=="pyw" (where pyw >nul 2>&1 && set "PYWOK=1")
if /i "%PYWEXE%"=="pythonw" (where pythonw >nul 2>&1 && set "PYWOK=1")
if not defined PYWOK if exist "%PYWEXE%" set "PYWOK=1"
if not defined PYWOK set "PYWEXE=%PYEXE%"
exit /b
"""


def build_bat() -> str:
    """生成完整 bat 文本：启动器 + 内嵌源码块"""
    parts = [LAUNCHER.rstrip("\n"), "", "###PYCODE###"]
    for src_name, embed_name in EMBED_FILES:
        path = os.path.join(SRC_DIR, src_name)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read().replace("\r\n", "\n").rstrip("\n")
        parts.append(MARKER_HEAD % embed_name)
        parts.append(content)
    return "\n".join(parts) + "\n"


def extract(bat_text: str) -> dict:
    """按 bat 的提取规则（PowerShell 行号切片）还原内嵌源码。键为嵌入名。"""
    embed_names = [name for _, name in EMBED_FILES]
    lines = bat_text.replace("\r\n", "\n").split("\n")
    idx = {}
    for i, line in enumerate(lines):
        for name in embed_names:
            if line.strip() == MARKER_HEAD % name:
                idx[name] = i
    if len(idx) != len(embed_names):
        raise RuntimeError("marker 缺失: %s" % (set(embed_names) - set(idx)))
    out = {}
    for pos, name in enumerate(embed_names):
        start = idx[name] + 1
        if pos + 1 < len(embed_names):
            end = idx[embed_names[pos + 1]]  # 到下一个 marker（不含）
        else:
            end = len(lines)  # 最后一个：到文件末尾
        out[name] = "\n".join(lines[start:end]).rstrip("\n")
    return out


def verify(bat_text: str) -> bool:
    """内嵌副本与 src/ 源码逐字节比对"""
    ok = True
    embedded = extract(bat_text)
    for src_name, embed_name in EMBED_FILES:
        with open(os.path.join(SRC_DIR, src_name), "r", encoding="utf-8") as f:
            src = f.read().replace("\r\n", "\n").rstrip("\n")
        if embedded[embed_name] != src:
            ok = False
            print("[不一致] src/%s → 内嵌 %s：两份内容不同" % (src_name, embed_name))
        else:
            print("[一致] src/%s → 内嵌 %s（%d 行）" % (src_name, embed_name, src.count("\n") + 1))
    return ok


def main():
    parser = argparse.ArgumentParser(description="同步 src/*.py 到 DataBackupFTPServer.bat")
    parser.add_argument("--check", action="store_true", help="只检查是否已同步，不写文件")
    args = parser.parse_args()

    if args.check:
        if not os.path.exists(BAT_PATH):
            print("[错误] 找不到 %s" % BAT_PATH)
            return 1
        with open(BAT_PATH, "r", encoding="utf-8") as f:
            bat_text = f.read()
        return 0 if verify(bat_text) else 1

    bat_text = build_bat()
    if not verify(bat_text):
        print("[错误] 生成结果自检未通过，未写入")
        return 1
    # newline="\r\n" 保证 bat 为 CRLF；encoding 不带 BOM（cmd 解析更稳）
    with open(BAT_PATH, "w", encoding="utf-8", newline="\r\n") as f:
        f.write(bat_text)
    size = os.path.getsize(BAT_PATH)
    total = bat_text.count("\n") + 1
    print("[完成] 已写入 %s（%d 行 / %d 字节，无 BOM + CRLF）" % (BAT_PATH, total, size))
    return 0


if __name__ == "__main__":
    sys.exit(main())
