@echo off
chcp 65001 >nul
setlocal EnableExtensions EnableDelayedExpansion
set "SCRIPT_VER=2.0"
title DataBackup Companion - FTP Backup Server v2.0 (GUI)

REM ============================================================
REM  DataBackup Companion - FTP Backup Server (Windows, GUI)
REM
REM  Original idea by Coolapk user @miaocuijiao12448
REM    https://www.coolapk.com/feed/73346386
REM  Maintained by boluo4169-commits (DataBackup custom)
REM    https://github.com/boluo4169-commits/Android-DataBackup-custom
REM  License: MIT
REM
REM  This .bat is a self-contained launcher (no exe, no install):
REM    1. Auto request admin rights (UAC) - needed for firewall rules
REM    2. Locate or auto-install Python, install pyftpdlib if missing
REM    3. Open the firewall ports (2121 + passive 60000-60100)
REM    4. Extract the embedded Python sources and launch the GUI
REM       (fill in account / password / folder, then click Start)
REM
REM  Usage:
REM    Double-click to launch the GUI (no prompts, everything in the window)
REM    CLI: this.bat <username> <password> <backup_dir>   (prefills the GUI)
REM    Diagnose: this.bat --diagnose [backup_dir]         (no GUI, no admin)
REM
REM  MAINTAINERS: the embedded sources at the bottom are generated by
REM    tools/sync_bat.py - never edit them by hand.
REM ============================================================

REM ---------- request admin rights (firewall rules need them) ----------
REM Diagnose mode: skip UAC (admin not needed for --diagnose)
if /i "%~1"=="--diagnose" goto :admin_ok
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo 正在请求管理员权限...
    powershell -NoProfile -Command "$a=@(); if('%~1' -ne ''){$a+='%~1'}; if('%~2' -ne ''){$a+='%~2'}; if('%~3' -ne ''){$a+='%~3'}; Start-Process -FilePath '%~f0' -ArgumentList $a -Verb RunAs"
    exit /b
)
:admin_ok

echo.
echo   DataBackup Companion - FTP 数据服务器 (GUI)  v%SCRIPT_VER%
echo   ------------------------------------------------------
echo   原始创意 : 酷安 @喵脆角12448
echo   重构维护 : boluo4169-commits (酷安 @骏冲冲)
echo   项目地址 : https://github.com/boluo4169-commits/Android-DataBackup-custom
echo   许可     : MIT
echo.

REM ---------- port pre-check (informational only) ----------
netstat -ano | findstr ":2121" >nul 2>&1
if %errorlevel% equ 0 echo [提示] 端口 2121 可能已被占用, 若启动失败请改端口或关闭占用程序。

REM ---------- locate Python, install if missing ----------
REM Prefer the official launcher (py -3) and standard install paths over bare
REM "python": in some environments PATH's python is a venv/conda shim without
REM pip or pyftpdlib, which would be misreported as "install failed".
set "PYEXE="
if exist "%LOCALAPPDATA%\Programs\Python\Python312\python.exe" set "PYEXE=%LOCALAPPDATA%\Programs\Python\Python312\python.exe"
if not defined PYEXE if exist "%LOCALAPPDATA%\Programs\Python\Python313\python.exe" set "PYEXE=%LOCALAPPDATA%\Programs\Python\Python313\python.exe"
if not defined PYEXE if exist "%LOCALAPPDATA%\Programs\Python\Python311\python.exe" set "PYEXE=%LOCALAPPDATA%\Programs\Python\Python311\python.exe"
if not defined PYEXE (where py >nul 2>&1 && set "PYEXE=py -3")
if not defined PYEXE (where python >nul 2>&1 && set "PYEXE=python")
if defined PYEXE (%PYEXE% -c "import sys" >nul 2>&1 && goto :python_ok)
set "PYEXE="
echo 未检测到 Python, 正在自动安装 Python 3.12, 请稍候...
winget install --id Python.Python.3.12 -e --silent --scope user --accept-package-agreements --accept-source-agreements --disable-interactivity
if exist "%LOCALAPPDATA%\Programs\Python\Python312\python.exe" set "PYEXE=%LOCALAPPDATA%\Programs\Python\Python312\python.exe"
if not defined PYEXE (where py >nul 2>&1 && set "PYEXE=py -3")
if not defined PYEXE (where python >nul 2>&1 && set "PYEXE=python")
if defined PYEXE (%PYEXE% -c "import sys" >nul 2>&1 && goto :python_ok)
echo [错误] Python 仍然不可用, 请手动安装后重新运行脚本:
echo         winget install --id Python.Python.3.12 -e
pause
exit /b 1
:python_ok
echo Python 路径: %PYEXE%

REM ---------- ensure pyftpdlib is installed ----------
:ensure_ftpdep
%PYEXE% -c "import pyftpdlib" >nul 2>&1
if not errorlevel 1 goto :ftpdep_ok
echo 正在使用国内镜像源安装 pyftpdlib...
%PYEXE% -m pip install pyftpdlib -i https://pypi.tuna.tsinghua.edu.cn/simple --disable-pip-version-check -q
%PYEXE% -c "import pyftpdlib" >nul 2>&1
if not errorlevel 1 goto :ftpdep_ok
echo 国内镜像失败, 尝试官方 PyPI 源...
%PYEXE% -m pip install pyftpdlib --disable-pip-version-check -q
%PYEXE% -c "import pyftpdlib" >nul 2>&1
if not errorlevel 1 goto :ftpdep_ok
echo 尝试用户目录安装...
%PYEXE% -m pip install pyftpdlib --user -i https://pypi.tuna.tsinghua.edu.cn/simple --disable-pip-version-check -q
%PYEXE% -c "import pyftpdlib" >nul 2>&1
if not errorlevel 1 goto :ftpdep_ok
REM Current interpreter really can not install it (e.g. a venv python with no pip).
REM Fall back to the official launcher once, then give up.
if defined FTPDEP_RETRIED goto :ftpdep_fail
if /i "%PYEXE%"=="py -3" goto :ftpdep_fail
where py >nul 2>&1
if errorlevel 1 goto :ftpdep_fail
set "PYEXE=py -3"
set "FTPDEP_RETRIED=1"
echo 当前解释器无法安装依赖, 换用官方 launcher (py -3) 重试...
goto :ensure_ftpdep
:ftpdep_fail
echo [错误] pyftpdlib 安装失败, 请手动执行:
echo         %PYEXE% -m pip install pyftpdlib -i https://pypi.tuna.tsinghua.edu.cn/simple
pause
exit /b 1
:ftpdep_ok
echo pyftpdlib: OK

REM ---------- firewall rules (2121 + passive 60000-60100); diagnose mode skips ----------
if /i "%~1"=="--diagnose" (
    echo 诊断模式: 跳过防火墙配置
) else (
    netsh advfirewall firewall show rule name="DataBackup FTP 2121" >nul 2>&1
    if errorlevel 1 netsh advfirewall firewall add rule name="DataBackup FTP 2121" dir=in action=allow protocol=TCP localport=2121
    netsh advfirewall firewall show rule name="DataBackup FTP Passive 60000-60100" >nul 2>&1
    if errorlevel 1 netsh advfirewall firewall add rule name="DataBackup FTP Passive 60000-60100" dir=in action=allow protocol=TCP localport=60000-60100
    echo 防火墙规则: 已就绪
)

REM ---------- extract the embedded python sources (ftp_core.py + ftp_server.py) ----------
set "WKDIR=%TEMP%\DataBackupFTP_server"
if not exist "%WKDIR%" mkdir "%WKDIR%"
powershell -NoProfile -Command "$l=Get-Content -LiteralPath '%~f0' -Encoding UTF8; $a=($l|Select-String '^###FILE:ftp_core.py###$').LineNumber; $b=($l|Select-String '^###FILE:ftp_server.py###$').LineNumber; if(-not $a -or -not $b){Write-Error 'FILE markers not found'; exit 1}; [IO.File]::WriteAllLines('%WKDIR%\ftp_core.py', $l[$a..($b-2)]); [IO.File]::WriteAllLines('%WKDIR%\ftp_server.py', $l[$b..($l.Count-1)])"
if errorlevel 1 (
    echo [错误] 内嵌服务端代码提取失败
    pause
    exit /b 1
)

REM ---------- security notice ----------
echo.
echo **********************************************************************
echo   注意: FTP 为明文协议, 请仅在可信的家庭/办公局域网内使用,
echo         不要将端口暴露到公网。传输完成后可直接关闭本窗口。
echo **********************************************************************

REM ---------- launch ----------
set "PYTHONIOENCODING=utf-8"

REM Diagnose mode: keep the console (the report is printed here). No pause so it
REM can also be driven non-interactively (scripts / CI).
if /i "%~1"=="--diagnose" (
    echo 正在生成诊断包...
    %PYEXE% -X utf8 -u "%WKDIR%\ftp_server.py" %*
    echo.
    echo 诊断包已生成, 可以关闭本窗口
    exit /b
)

REM GUI mode: hand off to a windowed interpreter (pythonw / pyw) and let this
REM console exit, so the user only sees the GUI window. Startup errors are
REM reported by the GUI itself; anything that must be seen here (Python /
REM pyftpdlib install failures) already happened above.
call :pick_windowed
echo 正在启动图形界面, 填好账号密码与目录后点「开启」...
start "" %PYWEXE% -X utf8 "%WKDIR%\ftp_server.py" %*
exit /b

:pick_windowed
REM Derive the windowed twin of %PYEXE% (python.exe -> pythonw.exe, py -3 -> pyw -3).
set "PYWEXE="
if /i "%PYEXE%"=="py -3" set "PYWEXE=pyw -3"
if /i "%PYEXE%"=="py" set "PYWEXE=pyw"
if /i "%PYEXE%"=="python" set "PYWEXE=pythonw"
if not defined PYWEXE set "PYWEXE=%PYEXE:python.exe=pythonw.exe%"
REM Check it exists instead of probing it: pyw / pythonw detach immediately, so
REM running them gives no reliable errorlevel. Fall back to the console one when
REM the windowed twin is missing.
set "PYWOK="
if /i "%PYWEXE%"=="pyw -3" (where pyw >nul 2>&1 && set "PYWOK=1")
if /i "%PYWEXE%"=="pyw" (where pyw >nul 2>&1 && set "PYWOK=1")
if /i "%PYWEXE%"=="pythonw" (where pythonw >nul 2>&1 && set "PYWOK=1")
if not defined PYWOK if exist "%PYWEXE%" set "PYWOK=1"
if not defined PYWOK set "PYWEXE=%PYEXE%"
exit /b

###PYCODE###
###FILE:ftp_core.py###
# -*- coding: utf-8 -*-
"""DataBackup Companion — FTP 服务核心（无 UI 依赖）。

GUI 入口（DataBackupFTPServer.py）与 bat 内嵌副本、CI 无头冒烟共用本模块，
保证「逻辑只有一份」。本文件不含任何 print/input，输出一律通过回调或返回值交给调用方。

Original idea by Coolapk @喵脆角12448, refactored by boluo4169-commits (Coolapk @骏冲冲). MIT.
"""
import datetime
import json
import logging
import os
import platform
import secrets
import shutil
import socket
import string
import subprocess
import sys
import threading
import time
import zipfile

try:
    from pyftpdlib.authorizers import DummyAuthorizer
    from pyftpdlib.handlers import FTPHandler
    from pyftpdlib.servers import FTPServer
except ImportError:  # 由调用方决定如何提示（GUI 弹窗 / 控制台打印）
    DummyAuthorizer = FTPHandler = FTPServer = None


# companion 自身的版本号（独立于 App；更新时手动 bump 这里）
COMPANION_VERSION = "v2.0"
REPO_URL = "https://github.com/boluo4169-commits/Android-DataBackup-custom"

DEFAULT_PORT = int(os.environ.get("FTP_PORT", "2121"))
PASSIVE_MIN = int(os.environ.get("FTP_PASSIVE_MIN", "60000"))
PASSIVE_COUNT = 101
PASSIVE_PORTS = range(PASSIVE_MIN, PASSIVE_MIN + PASSIVE_COUNT)
DEFAULT_USER = "databackup"
FTP_PERM = "elradfmw"  # elr 读 + adfmw 写（无 M/T：不允许改权限与文件时间）

CONFIG_PATH = os.path.join(os.path.expanduser("~"), ".databackup_ftp_config.json")
LEGACY_CRED_PATH = os.path.join(os.path.expanduser("~"), ".databackup_ftp_cred")


def dependency_ok():
    """pyftpdlib 是否可用"""
    return FTPServer is not None


def app_build_tag():
    """构建所对应的 App release tag（CI 注入 _tool_version.py；bat/源码直跑时为 dev）"""
    try:
        from _tool_version import APP_BUILD_TAG
        return APP_BUILD_TAG
    except Exception:
        return "dev"


def check_update():
    """查 GitHub 最新 release。返回 (最新 tag 或 None, 是否比本构建更新)。

    companion 跟随 App 发布节奏（exe 附加在 App release），所以这里比的是 App tag。
    """
    tag = app_build_tag()
    if tag == "dev":
        return None, False
    try:
        import urllib.request
        req = urllib.request.Request(
            REPO_URL.replace("https://", "https://api.") + "/releases/latest",
            headers={"User-Agent": "DataBackupCompanion"},
        )
        with urllib.request.urlopen(req, timeout=8) as r:
            latest = json.load(r).get("tag_name", "")
        return latest, bool(latest and latest != tag)
    except Exception:
        return None, False


def default_backup_dir():
    """默认备份目录：有 D 盘用 D:\\DataBackupFTP，否则 C:\\DataBackupFTP"""
    return r"D:\DataBackupFTP" if os.path.exists("D:\\") else r"C:\DataBackupFTP"


def gen_password(length=8):
    """生成随机密码（与旧版行为一致：大小写字母 + 数字）"""
    alphabet = string.digits + string.ascii_letters
    return "".join(secrets.choice(alphabet) for _ in range(length))


def primary_lan_ip():
    """默认路由出口 IP —— 手机要填的通常就是它。

    UDP connect 不会真的发包，只是让内核选好出接口，从而拿到本机在该路由上的地址。
    """
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
        finally:
            s.close()
    except Exception:
        return ""


def list_lan_ips():
    """本机 IPv4 候选地址。

    **默认路由出口 IP 排第一位**（手机优先填它），其余的（VMware VMnet、Clash TUN
    等虚拟网卡）排在后面。旧版只是按 getaddrinfo 顺序排，导致虚拟网卡经常排在首位。
    """
    ips = []
    primary = primary_lan_ip()
    if primary and not primary.startswith("127.") and not primary.startswith("169.254."):
        ips.append(primary)
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            ip = info[4][0]
            if ip.startswith("127.") or ip.startswith("169.254."):
                continue
            if ip not in ips:
                ips.append(ip)
    except Exception:
        pass
    return ips or ["127.0.0.1"]


def port_in_use(port):
    """检查端口是否被占用（尝试绑定即知）"""
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.bind(("0.0.0.0", port))
        return False
    except OSError:
        return True
    finally:
        s.close()


# ---------------------------------------------------------------------------
# 配置持久化：单个 json（旧版明文 cred 文件自动迁移）
# ---------------------------------------------------------------------------

DEFAULT_CONFIG = {
    "user": DEFAULT_USER,
    "password": "",
    "port": DEFAULT_PORT,
    "backup_dir": "",
    "dir_history": [],
    "theme": "light",  # light / dark
}
THEMES = ("light", "dark")


def load_config():
    """读取配置；无配置时回退旧版 cred 文件的账号密码。返回 dict（字段已归一化）。"""
    cfg = dict(DEFAULT_CONFIG)
    cfg["dir_history"] = []
    try:
        if os.path.exists(CONFIG_PATH):
            with open(CONFIG_PATH, "r", encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict):
                if isinstance(data.get("user"), str):
                    cfg["user"] = data["user"]
                if isinstance(data.get("password"), str):
                    cfg["password"] = data["password"]
                if isinstance(data.get("port"), int) and 1 <= data["port"] <= 65535:
                    cfg["port"] = data["port"]
                if isinstance(data.get("backup_dir"), str):
                    cfg["backup_dir"] = data["backup_dir"]
                hist = data.get("dir_history")
                if isinstance(hist, list):
                    cfg["dir_history"] = [d for d in hist if isinstance(d, str) and d]
                if data.get("theme") in THEMES:
                    cfg["theme"] = data["theme"]
        else:
            # 旧版 cred 文件（仅账号密码）迁移，首次保存后即写入新配置文件
            if os.path.exists(LEGACY_CRED_PATH):
                with open(LEGACY_CRED_PATH, "r", encoding="utf-8") as f:
                    old = json.load(f)
                if isinstance(old, dict) and old.get("user") and old.get("password"):
                    cfg["user"] = old["user"]
                    cfg["password"] = old["password"]
    except Exception:
        pass
    if not cfg["user"]:
        cfg["user"] = DEFAULT_USER
    if not cfg["backup_dir"]:
        cfg["backup_dir"] = default_backup_dir()
    return cfg


def save_config(user, password, port, backup_dir, dir_history=None, theme="light"):
    """保存配置（明文，仅限可信局域网场景；与旧版 cred 文件同口径）"""
    data = {
        "user": user,
        "password": password,
        "port": int(port),
        "backup_dir": backup_dir,
        "dir_history": list(dir_history or [])[:10],
        "theme": theme if theme in THEMES else "light",
    }
    try:
        with open(CONFIG_PATH, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return True
    except Exception:
        return False


# ---------------------------------------------------------------------------
# FTP 服务：启停封装（GUI 的「开启 / 停止」按钮直接调它）
# ---------------------------------------------------------------------------

class FtpService:
    """FTP 服务生命周期封装。

    on_log(text)   : 运行日志（连接、命令、传输），由调用方决定写到哪
    on_conn(delta) : 在线连接数变化（+1 / -1），失败不影响服务
    """

    def __init__(self, on_log=None, on_conn=None):
        self._on_log = on_log
        self._on_conn = on_conn
        self._server = None
        self._thread = None
        self.user = ""
        self.password = ""
        self.backup_dir = ""
        self.port = DEFAULT_PORT
        self.lan_ips = []
        self.connections = 0
        if on_log is not None:
            self._silence_library_logger()

    @staticmethod
    def _silence_library_logger():
        """日志统一走 on_log 回调，关掉 pyftpdlib 自带的 stderr 输出，避免重复刷屏。

        要点：pyftpdlib 的 is_logging_configured() 只看「logger 有没有 handler」，
        没有就自己挂一个 StreamHandler 到 stderr。所以这里挂一个 NullHandler 顶替，
        否则 FTPServer 构造时会重配 logger（level 拉回 INFO）并重新开始打印。
        """
        try:
            lib_logger = logging.getLogger("pyftpdlib")
            lib_logger.handlers.clear()
            lib_logger.addHandler(logging.NullHandler())
            lib_logger.propagate = False
            lib_logger.setLevel(logging.CRITICAL)
        except Exception:
            pass

    # -- 内部 ---------------------------------------------------------------
    def _log(self, msg):
        if self._on_log is not None:
            try:
                self._on_log(str(msg).rstrip())
            except Exception:
                pass

    def _make_handler(self):
        """动态生成 handler 子类：日志外抛 + 连接计数，其余照抄原参数"""
        service = self

        def _prefix(handler):
            """与 pyftpdlib 默认 log_prefix 对齐的前缀：用户名@IP"""
            ip = getattr(handler, "remote_ip", "") or ""
            name = getattr(handler, "username", "") or "-"
            return ("%s@%s" % (name, ip)) if ip else ""

        class CompanionFTPHandler(FTPHandler):
            # pyftpdlib 2.2.0 签名: log(msg, logfun=logger.info) / logerror(msg)
            # 覆盖 log 即覆盖「登录成功 + 传输完成 + 白名单命令(DELE/RMD/CWD/MKD…)」；
            # logline 是 DEBUG 开关控制的逐条命令流，不覆盖（日志区没必要刷屏）。
            def log(self, msg, logfun=None):
                service._log("%s %s" % (_prefix(self), msg))

            def logerror(self, msg):
                service._log("%s [错误] %s" % (_prefix(self), msg))

            def on_connect(self):
                service.connections += 1
                service._log("客户端已连接: %s" % self.remote_ip)
                if service._on_conn is not None:
                    try:
                        service._on_conn(service.connections)
                    except Exception:
                        pass

            def on_disconnect(self):
                service.connections = max(0, service.connections - 1)
                service._log("客户端已断开: %s" % self.remote_ip)
                if service._on_conn is not None:
                    try:
                        service._on_conn(service.connections)
                    except Exception:
                        pass

        authorizer = DummyAuthorizer()
        authorizer.add_user(
            self.user, self.password, self.backup_dir, perm=FTP_PERM
        )
        CompanionFTPHandler.authorizer = authorizer
        # 不要设 masquerade_address！pyftpdlib 默认用「客户端连进来的那个本机地址」
        # （dispatchers.py: local_ip = cmd_channel.socket.getsockname()[0]）作为 PASV 地址，
        # 多网卡机器上这才是对的。旧版硬设成 lan_ips[0]（虚拟机网卡常排首位）→ 手机填
        # 真实网卡地址连进来后，PASV 阶段被指向虚拟网卡地址，传输必失败。
        CompanionFTPHandler.masquerade_address = None
        CompanionFTPHandler.passive_ports = PASSIVE_PORTS
        CompanionFTPHandler.banner = "DataBackup Companion FTP server ready."
        # pyftpdlib 默认 300s 控制连接空闲超时：备份大应用（微信 user 等数 GB）上传期间
        # 控制连接长时间无命令，会被服务器主动断开 → 客户端报 "Software caused connection abort"。
        # 禁用空闲超时（0 = 不超时），由客户端超时兜底。
        CompanionFTPHandler.timeout = 0
        return CompanionFTPHandler

    # -- 对外 ---------------------------------------------------------------
    @property
    def is_running(self):
        return self._server is not None

    def start(self, user, password, backup_dir, port):
        """启动服务。返回 (是否成功, 提示文本)；异常一律转成文本，不抛出。"""
        if self.is_running:
            return False, "服务已在运行"
        if not dependency_ok():
            return False, "缺少依赖 pyftpdlib，请先执行  pip install pyftpdlib"
        if not user:
            return False, "用户名不能为空"
        if not password:
            return False, "密码不能为空（可点「随机」生成）"
        if not backup_dir:
            return False, "请先选择备份保存目录"
        if not (isinstance(port, int) and 1 <= port <= 65535):
            return False, "端口需为 1 ~ 65535"
        if not os.path.isdir(backup_dir):
            try:
                os.makedirs(backup_dir, exist_ok=True)
            except Exception as e:
                return False, "目录不存在且无法创建: %s (%s)" % (backup_dir, e)
        if port_in_use(port):
            return False, "端口 %d 已被占用（可能已有 FTP 服务在运行）" % port

        self.user = user
        self.password = password
        self.backup_dir = backup_dir
        self.port = port
        self.lan_ips = list_lan_ips()
        self.connections = 0

        try:
            handler = self._make_handler()
            server = FTPServer(("0.0.0.0", port), handler)
        except Exception as e:
            self._server = None
            return False, "启动失败: %s" % e

        if self._on_log is not None:
            self._silence_library_logger()  # 兜底再压一次（构造过程可能重配过 logger）

        self._server = server
        self._thread = threading.Thread(target=server.serve_forever, daemon=True)
        self._thread.start()
        self._log("服务已启动，监听 0.0.0.0:%d，根目录 %s" % (port, backup_dir))
        return True, "服务已启动"

    def stop(self, wait=True):
        """停止服务。返回是否确实执行了停止。"""
        if not self.is_running:
            return False
        try:
            self._server.close_all()
        except Exception as e:
            self._log("停止服务时出现异常: %s" % e)
        if wait and self._thread is not None:
            try:
                self._thread.join(timeout=5)
            except Exception:
                pass
        self._server = None
        self._thread = None
        self.connections = 0
        self._log("服务已停止")
        return True

    def connection_card(self):
        """手机端填写用的连接信息（列表形式，每行一项）"""
        ips = self.lan_ips or list_lan_ips()
        primary = ips[0]
        others = ips[1:]
        rows = [("地址", "%s（推荐）" % primary)]
        if others:
            rows.append(
                ("备用地址", " 或 ".join(others) + "（多半是虚拟网卡，手机连不上）")
            )
        rows += [
            ("端口", str(self.port)),
            ("用户名", self.user),
            ("密码", self.password),
            ("远程目录", "/"),
            ("传输模式", "被动(PASV)"),
        ]
        return rows

    def connection_card_text(self):
        return "\n".join("%s: %s" % (k, v) for k, v in self.connection_card())


def run_selftest(user, password, port):
    """本地回环自检：连接 → 登录 → 上传 → 列表 → 删除。成功返回 True。"""
    import ftplib
    import io

    name = "__selftest__.txt"
    ftp = None
    try:
        for _ in range(10):
            try:
                ftp = ftplib.FTP()
                ftp.connect("127.0.0.1", port, timeout=5)
                ftp.login(user, password)
                break
            except Exception:
                ftp = None
                time.sleep(0.5)
        if ftp is None:
            return False
        ftp.set_pasv(True)
        ftp.storbinary("STOR " + name, io.BytesIO(b"DataBackup selftest OK\n"))
        names = ftp.nlst()
        ftp.delete(name)
        ftp.quit()
        return name in names
    except Exception:
        return False


# ---------------------------------------------------------------------------
# 诊断模式（--diagnose）：
# 一键导出「环境信息 + FTP 状态 + 备份文件清单 + 完整性检查」，与手机端
# 「导出日志」组成双向反馈材料。用户反馈问题时运行一次，把生成的 zip 发来即可。
# ---------------------------------------------------------------------------

def human_size(num):
    """字节数转可读大小"""
    try:
        num = float(num)
    except Exception:
        return "?"
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if abs(num) < 1024.0 or unit == "TiB":
            return "%.1f %s" % (num, unit)
        num /= 1024.0
    return "%.1f B" % num


def collect_environment(backup_dir, port):
    """环境信息文本"""
    lines = []
    lines.append("DataBackup Companion 诊断报告")
    lines.append("生成时间: %s" % datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    lines.append("=" * 56)
    lines.append("[环境]")
    lines.append("系统: %s" % platform.platform())
    lines.append("Python: %s" % sys.version.replace("\n", " "))
    lines.append("主机名: %s" % socket.gethostname())
    lines.append("局域网 IP: %s" % (" 或 ".join(list_lan_ips())))
    lines.append("备份目录: %s" % backup_dir)
    try:
        usage = shutil.disk_usage(os.path.abspath(backup_dir) if os.path.exists(backup_dir) else ".")
        lines.append("磁盘空间: 总 %s / 剩余 %s" % (human_size(usage.total), human_size(usage.free)))
    except Exception as e:
        lines.append("磁盘空间: 读取失败 (%s)" % e)
    lines.append("端口 %d: %s" % (port, "已被占用（可能有其他 FTP 服务）" if port_in_use(port) else "空闲"))
    lines.append("被动端口段: %d ~ %d" % (PASSIVE_MIN, PASSIVE_MIN + PASSIVE_COUNT - 1))
    # 防火墙当前配置文件状态（可能需管理员，失败则记录）
    try:
        out = subprocess.run(
            ["netsh", "advfirewall", "show", "currentprofile"],
            capture_output=True, text=True, timeout=10, errors="replace",
        ).stdout
        lines.append("防火墙(当前配置): %s" % " ".join(out.split()) if out.strip() else "无输出")
    except Exception as e:
        lines.append("防火墙: 查询失败 (%s)" % e)
    return "\n".join(lines) + "\n"


def collect_ftp_status(user, port):
    """FTP 服务状态文本（密码不输出）"""
    lines = []
    lines.append("[FTP 服务]")
    lines.append("用户名: %s（密码不输出）" % (user or DEFAULT_USER))
    lines.append("监听端口: %d" % port)
    lines.append("端口状态: %s" % ("已被占用" if port_in_use(port) else "空闲"))
    lines.append("自检: 诊断模式未启动服务，跳过（正常启动时会自动自检）")
    return "\n".join(lines) + "\n"


def walk_entries(root):
    """遍历目录，返回 (相对路径, 是否目录, 大小) 列表，按路径排序。
    跳过历史诊断包（DataBackup_diagnose_*.zip），避免诊断包互相包含。"""
    entries = []
    if not os.path.isdir(root):
        return entries
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        rel = os.path.relpath(dirpath, root)
        for d in sorted(dirnames):
            entries.append((os.path.join(rel, d) if rel != "." else d, True, 0))
        for f in sorted(filenames):
            if f.startswith("DataBackup_diagnose_") and f.endswith(".zip"):
                continue
            full = os.path.join(dirpath, f)
            try:
                size = os.path.getsize(full)
            except OSError:
                size = -1
            entries.append((os.path.join(rel, f) if rel != "." else f, False, size))
    return entries


def group_stats(entries):
    """按顶级目录分组统计：返回 {group: (count_files, total_size)}"""
    stats = {}
    for rel, is_dir, size in entries:
        if is_dir:
            continue
        group = rel.split(os.sep)[0] if os.sep in rel else "(根目录)"
        cnt, total = stats.get(group, (0, 0))
        stats[group] = (cnt + 1, total + max(size, 0))
    return stats


def collect_file_inventory(backup_dir):
    """文件清单 + 分组统计 + 0 字节文件"""
    entries = walk_entries(backup_dir)
    lines = []
    lines.append("[备份文件清单]")
    stats = group_stats(entries)
    for group in sorted(stats):
        cnt, total = stats[group]
        lines.append("%s/: %d 个文件, 共 %s" % (group, cnt, human_size(total)))
    lines.append("")
    lines.append("[目录树]")
    for rel, is_dir, size in entries:
        if is_dir:
            lines.append("  [目录] %s" % rel)
        else:
            lines.append("  %s  (%s)" % (rel, human_size(size)))
    zero_files = [rel for rel, is_dir, size in entries if not is_dir and size == 0]
    lines.append("")
    lines.append("[0 字节文件]")
    if zero_files:
        for f in zero_files:
            lines.append("  %s" % f)
    else:
        lines.append("  无")
    return "\n".join(lines) + "\n"


def is_valid_json(path):
    try:
        # utf-8-sig 兼容带 BOM 的 json（部分工具写入会带 BOM）
        with open(path, "r", encoding="utf-8-sig") as fh:
            json.load(fh)
        return True
    except Exception:
        return False


def collect_integrity(backup_dir):
    """深度完整性检查：config json 合法性 + .md5 与归档配对 + 迁移包清单。
    返回 (文本, 异常列表)"""
    lines = []
    anomalies = []
    lines.append("[完整性检查]")

    apps_root = os.path.join(backup_dir, "apps")
    if os.path.isdir(apps_root):
        app_dirs = sorted(
            d for d in os.listdir(apps_root)
            if os.path.isdir(os.path.join(apps_root, d))
        )
        lines.append("应用备份（apps/）: %d 个应用" % len(app_dirs))
        for app in app_dirs:
            app_path = os.path.join(apps_root, app)
            version_dirs = sorted(
                d for d in os.listdir(app_path)
                if os.path.isdir(os.path.join(app_path, d))
            )
            for ver in version_dirs:
                ver_path = os.path.join(app_path, ver)
                files = [f for f in os.listdir(ver_path) if os.path.isfile(os.path.join(ver_path, f))]
                config_ok = os.path.exists(os.path.join(ver_path, "package_restore_config.json"))
                archives = [f for f in files if f.endswith((".tar", ".tar.zst", ".zst"))]
                md5s = [f for f in files if f.endswith(".md5")]
                # md5 配对：每个归档应有同名 .md5；每个 .md5 应有对应归档
                archive_no_md5 = [f for f in archives if (f + ".md5") not in md5s]
                md5_no_archive = [f for f in md5s if f[: -len(".md5")] not in archives]
                zero = [f for f in files if os.path.getsize(os.path.join(ver_path, f)) == 0]
                issues = []
                if not config_ok:
                    issues.append("config 缺失")
                if archive_no_md5:
                    issues.append("归档缺 md5: %s" % ",".join(archive_no_md5))
                if md5_no_archive:
                    issues.append("md5 无对应归档: %s" % ",".join(md5_no_archive))
                if zero:
                    issues.append("0 字节: %s" % ",".join(zero))
                cfg_path = os.path.join(ver_path, "package_restore_config.json")
                if config_ok and not is_valid_json(cfg_path):
                    issues.append("config 不是合法 JSON")
                if issues:
                    lines.append("  x %s/%s: %s" % (app, ver, "; ".join(issues)))
                    anomalies.append("%s/%s: %s" % (app, ver, "; ".join(issues)))
                else:
                    lines.append("  - %s/%s: %d 归档, md5 配对 OK" % (app, ver, len(archives)))
    else:
        lines.append("应用备份（apps/）: 目录不存在（可能从未备份应用）")

    migration_dir = os.path.join(backup_dir, "migration")
    lines.append("")
    lines.append("[云端迁移包（migration/）]")
    if os.path.isdir(migration_dir):
        pkgs = sorted(
            f for f in os.listdir(migration_dir)
            if os.path.isfile(os.path.join(migration_dir, f))
        )
        if pkgs:
            for f in pkgs:
                size = os.path.getsize(os.path.join(migration_dir, f))
                lines.append("  %s  (%s)" % (f, human_size(size)))
        else:
            lines.append("  目录为空")
    else:
        lines.append("  目录不存在（尚未导出过云端迁移包）")

    lines.append("")
    lines.append("[异常汇总]")
    if anomalies:
        for a in anomalies:
            lines.append("  x %s" % a)
    else:
        lines.append("  无")

    return "\n".join(lines) + "\n", anomalies


def collect_summary_json(backup_dir, anomalies, port):
    """机器可读汇总（便于程序解析/快速核对）"""
    entries = walk_entries(backup_dir)
    stats = group_stats(entries)
    return {
        "generated_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "platform": platform.platform(),
        "backup_dir": backup_dir,
        "lan_ips": list_lan_ips(),
        "port": port,
        "port_in_use": port_in_use(port),
        "groups": {k: {"files": v[0], "total_bytes": v[1]} for k, v in stats.items()},
        "anomalies": anomalies,
    }


def create_diagnose_zip(user, backup_dir, port):
    """生成诊断 zip，返回 (zip 路径, 异常条数)；失败抛异常由调用方处理。
    注意：诊断包不再打印任何东西——GUI 与控制台各自决定怎么展示。"""
    backup_dir = backup_dir or default_backup_dir()
    os.makedirs(backup_dir, exist_ok=True)

    env_text = collect_environment(backup_dir, port)
    ftp_text = collect_ftp_status(user, port)
    inv_text = collect_file_inventory(backup_dir)
    integrity_text, anomalies = collect_integrity(backup_dir)
    summary = collect_summary_json(backup_dir, anomalies, port)

    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    zip_path = os.path.join(backup_dir, "DataBackup_diagnose_%s.zip" % ts)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("environment.txt", env_text, compress_type=zipfile.ZIP_DEFLATED)
        zf.writestr("ftp_status.txt", ftp_text, compress_type=zipfile.ZIP_DEFLATED)
        zf.writestr("file_inventory.txt", inv_text, compress_type=zipfile.ZIP_DEFLATED)
        zf.writestr("integrity_check.txt", integrity_text, compress_type=zipfile.ZIP_DEFLATED)
        zf.writestr(
            "diagnose.json",
            json.dumps(summary, ensure_ascii=False, indent=2),
            compress_type=zipfile.ZIP_DEFLATED,
        )
    return zip_path, anomalies
###FILE:ftp_server.py###
# -*- coding: utf-8 -*-
"""DataBackup Companion — FTP Backup Server (GUI, standalone executable).

界面化的 Windows FTP 备份服务器：填账号密码 → 选目录 → 点「开启」，
手机端照连接卡片填写即可。服务核心在 ftp_core.py（GUI / bat / CI 共用一份）。

Original idea by Coolapk @喵脆角12448, refactored by boluo4169-commits (Coolapk @骏冲冲). MIT.

Usage:
    DataBackupFTPServer.exe                        启动图形界面
    DataBackupFTPServer.exe <user> <pass> <dir>    以这些值预填界面
    DataBackupFTPServer.exe --diagnose [--backup-dir=<路径>]   无界面生成诊断包
    DataBackupFTPServer.exe --exit-after-selftest <user> <pass> <dir>  无界面自检（CI 冒烟）
"""
import os
import queue
import subprocess
import sys
import threading
import webbrowser

import ftp_core

APP_TITLE = "DataBackup Companion — FTP 数据服务器 %s" % ftp_core.COMPANION_VERSION
LOG_MAX_LINES = 800

# 浅/深两套配色（零依赖：ttk 用 clam 主题 + 手工配色，tk.Text 单独设色）
PALETTES = {
    "light": {
        "bg": "#F5F4F0", "field": "#FFFFFF", "text": "#2C2C2A", "muted": "#888780",
        "border": "#D3D1C7", "btn": "#EDEBE5", "btn_active": "#E2DFD7",
        "select": "#B5D4F4", "ok": "#0F6E56", "err": "#A32D2D",
    },
    "dark": {
        "bg": "#1F1F1E", "field": "#141413", "text": "#E8E6E1", "muted": "#8A8880",
        "border": "#4A4A47", "btn": "#2A2A28", "btn_active": "#34342F",
        "select": "#0C447C", "ok": "#5DCAA5", "err": "#F09595",
    },
}


def attach_parent_console():
    """--windowed 打包下从 cmd 运行时，把输出接回父控制台，使 --diagnose 仍可见。"""
    if sys.stdout is not None:
        return
    if os.name != "nt":
        return
    try:
        import ctypes
        if ctypes.windll.kernel32.AttachConsole(-1):
            sys.stdout = open("CONOUT$", "w", encoding="utf-8", buffering=1)
            sys.stderr = sys.stdout
    except Exception:
        pass


def out(text=""):
    """无界面模式的输出（无控制台时静默丢弃，不影响退出码）"""
    try:
        if sys.stdout is not None:
            print(text)
    except Exception:
        pass


# ---------------------------------------------------------------------------
# 无界面模式（CI 冒烟 / 诊断包）
# ---------------------------------------------------------------------------

def headless_diagnose(backup_dir, port):
    try:
        zip_path, anomalies = ftp_core.create_diagnose_zip(
            user="", backup_dir=backup_dir, port=port
        )
    except Exception as e:
        out("[诊断] 写入诊断包失败: %s" % e)
        return 1
    out("=" * 56)
    out("[诊断] 完成")
    out("  诊断包: %s" % zip_path)
    out("  异常数: %d" % len(anomalies))
    for a in anomalies[:20]:
        out("    x %s" % a)
    if len(anomalies) > 20:
        out("    ... 共 %d 条，详见 integrity_check.txt" % len(anomalies))
    out("  请将该 zip 发给维护者，配合手机端「导出日志」使用。")
    out("=" * 56)
    return 0


def headless_selftest(user, password, backup_dir, port):
    """CI 冒烟：起服务 → 回环自检 → 退出（0 通过 / 2 失败 / 1 启动失败）"""
    service = ftp_core.FtpService(on_log=lambda m: out(m))
    ok, msg = service.start(user, password, backup_dir, port)
    out("  启动     : %s" % msg)
    if not ok:
        return 1
    passed = ftp_core.run_selftest(user, password, port)
    out("  自检测试 : %s" % ("通过" if passed else "失败"))
    out("=" * 64)
    service.stop()
    return 0 if passed else 2


# ---------------------------------------------------------------------------
# 图形界面
# ---------------------------------------------------------------------------

def main_gui(preset_user="", preset_password="", preset_dir=""):
    import tkinter as tk
    from tkinter import filedialog, messagebox, scrolledtext, ttk

    cfg = ftp_core.load_config()
    user0 = preset_user or cfg["user"]
    password0 = preset_password or cfg["password"]
    dir0 = preset_dir or cfg["backup_dir"]
    port0 = cfg["port"]
    theme_name = cfg.get("theme", "light")
    if theme_name not in PALETTES:
        theme_name = "light"
    dir_history = list(cfg["dir_history"])
    if dir0 not in dir_history:
        dir_history.insert(0, dir0)

    log_queue = queue.Queue()
    service = ftp_core.FtpService(
        on_log=lambda m: log_queue.put(m),
        on_conn=lambda n: log_queue.put(("CONN", n)),
    )

    root = tk.Tk()
    root.title(APP_TITLE)
    root.geometry("760x600")
    root.minsize(680, 540)

    # ---------- 顶部：状态 + 启停 ----------
    top = ttk.Frame(root)
    top.pack(fill=tk.X, padx=12, pady=(12, 6))

    status_var = tk.StringVar(value="● 未启动")
    status_label = ttk.Label(top, textvariable=status_var)
    status_label.pack(side=tk.LEFT)

    stop_button = ttk.Button(top, text="停止", width=10, state=tk.DISABLED)
    stop_button.pack(side=tk.RIGHT, padx=(8, 0))
    start_button = ttk.Button(top, text="开启", width=10)
    start_button.pack(side=tk.RIGHT)

    # ---------- 表单 ----------
    form = ttk.Frame(root)
    form.pack(fill=tk.X, padx=12, pady=6)
    form.columnconfigure(0, weight=1)
    form.columnconfigure(1, weight=1)

    def labeled(parent, text, row, col):
        ttk.Label(parent, text=text).grid(
            row=row * 2, column=col, sticky=tk.W, padx=(0, 8), pady=(4, 2)
        )
        holder = ttk.Frame(parent)
        holder.grid(row=row * 2 + 1, column=col, sticky=tk.EW, padx=(0, 8), pady=(0, 6))
        return holder

    user_holder = labeled(form, "用户名", 0, 0)
    user_var = tk.StringVar(value=user0)
    ttk.Entry(user_holder, textvariable=user_var).pack(fill=tk.X)

    port_holder = labeled(form, "监听端口", 0, 1)
    port_var = tk.StringVar(value=str(port0))
    ttk.Entry(port_holder, textvariable=port_var).pack(fill=tk.X)

    pass_holder = labeled(form, "密码（手机端需填写此密码）", 1, 0)
    pass_row = ttk.Frame(pass_holder)
    pass_row.pack(fill=tk.X)
    pass_var = tk.StringVar(value=password0)

    def toggle_password():
        entry.configure(show="" if entry.cget("show") else "*")

    def random_password():
        pass_var.set(ftp_core.gen_password())
        entry.configure(show="")

    ttk.Button(pass_row, text="随机", width=6, command=random_password).pack(side=tk.RIGHT)
    ttk.Button(pass_row, text="显示", width=6, command=toggle_password).pack(side=tk.RIGHT, padx=(0, 4))
    entry = ttk.Entry(pass_row, textvariable=pass_var, show="*")
    entry.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 6))

    dir_holder = labeled(form, "备份保存目录（备份直接落在电脑硬盘）", 1, 1)
    dir_row = ttk.Frame(dir_holder)
    dir_row.pack(fill=tk.X)
    dir_var = tk.StringVar(value=dir0)
    dir_box = ttk.Combobox(dir_row, textvariable=dir_var, values=tuple(dir_history))
    dir_box.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 6))

    def pick_dir():
        path = filedialog.askdirectory(title="选择备份保存目录", initialdir=dir_var.get() or None)
        if path:
            dir_var.set(os.path.normpath(path))

    ttk.Button(dir_row, text="浏览", width=6, command=pick_dir).pack(side=tk.RIGHT)

    # ---------- 连接信息卡片 ----------
    card_box = ttk.LabelFrame(root, text="手机端照此填写（DataBackup → 云备份 → FTP）")
    card_box.pack(fill=tk.X, padx=12, pady=(6, 0))

    card_text = tk.Text(card_box, height=6, wrap=tk.NONE, font=("Consolas", 9))
    card_text.pack(fill=tk.X, padx=8, pady=(4, 4))
    card_text.configure(state=tk.DISABLED)

    card_buttons = ttk.Frame(card_box)
    card_buttons.pack(fill=tk.X, padx=8, pady=(0, 6))

    def refresh_card():
        service.user = user_var.get().strip()
        service.password = pass_var.get()
        try:
            service.port = int(port_var.get().strip())
        except ValueError:
            service.port = ftp_core.DEFAULT_PORT
        if not service.lan_ips:
            service.lan_ips = ftp_core.list_lan_ips()
        card_text.configure(state=tk.NORMAL)
        card_text.delete("1.0", tk.END)
        card_text.insert(tk.END, service.connection_card_text())
        card_text.configure(state=tk.DISABLED)

    def copy_card():
        text = card_text.get("1.0", tk.END).strip()
        if not text:
            return
        root.clipboard_clear()
        root.clipboard_append(text)
        log("[界面] 连接信息已复制到剪贴板")

    ttk.Button(card_buttons, text="复制全部", command=copy_card).pack(side=tk.LEFT)
    ttk.Button(card_buttons, text="刷新地址", command=refresh_card).pack(side=tk.LEFT, padx=(6, 0))

    # ---------- 日志 ----------
    log_box = ttk.LabelFrame(root, text="运行日志")
    log_box.pack(fill=tk.BOTH, expand=True, padx=12, pady=(8, 0))
    log_widget = scrolledtext.ScrolledText(log_box, height=10, wrap=tk.WORD, font=("Consolas", 9))
    log_widget.pack(fill=tk.BOTH, expand=True, padx=8, pady=6)
    log_widget.configure(state=tk.DISABLED)

    def log(text):
        """界面线程内写日志"""
        if not text:
            return
        log_widget.configure(state=tk.NORMAL)
        log_widget.insert(tk.END, text + "\n")
        # 超长时裁掉最早的行，避免长时间运行内存膨胀
        line_count = int(log_widget.index("end-1c").split(".")[0])
        if line_count > LOG_MAX_LINES:
            log_widget.delete("1.0", "%d.0" % (line_count - LOG_MAX_LINES))
        log_widget.see(tk.END)
        log_widget.configure(state=tk.DISABLED)

    # ---------- 底部 ----------
    bottom = ttk.Frame(root)
    bottom.pack(fill=tk.X, padx=12, pady=10)

    def open_backup_dir():
        path = dir_var.get().strip()
        if not path or not os.path.isdir(path):
            messagebox.showwarning("提示", "目录不存在：%s" % path)
            return
        try:
            os.startfile(path)  # type: ignore[attr-defined]
        except Exception as e:
            messagebox.showerror("打开失败", str(e))

    def make_diagnose():
        path = dir_var.get().strip() or ftp_core.default_backup_dir()
        log("[诊断] 正在收集环境与文件信息...")

        def work():
            try:
                zip_path, anomalies = ftp_core.create_diagnose_zip(
                    user=user_var.get().strip(), backup_dir=path, port=_current_port()
                )
                log_queue.put("[诊断] 诊断包已生成: %s（异常 %d 条）" % (zip_path, len(anomalies)))
                for a in anomalies[:10]:
                    log_queue.put("  x %s" % a)
            except Exception as e:
                log_queue.put("[诊断] 生成失败: %s" % e)

        threading.Thread(target=work, daemon=True).start()

    ttk.Button(bottom, text="生成诊断包", command=make_diagnose).pack(side=tk.LEFT)
    ttk.Button(bottom, text="打开备份目录", command=open_backup_dir).pack(side=tk.LEFT, padx=(8, 0))
    ttk.Button(
        bottom,
        text="项目主页",
        command=lambda: webbrowser.open(ftp_core.REPO_URL),
    ).pack(side=tk.LEFT, padx=(8, 0))

    is_dark_var = tk.BooleanVar(value=(theme_name == "dark"))
    theme_check = ttk.Checkbutton(bottom, text="深色模式", variable=is_dark_var)
    theme_check.pack(side=tk.LEFT, padx=(12, 0))

    ttk.Label(
        bottom,
        text="FTP 为明文协议，仅限可信局域网内使用",
    ).pack(side=tk.RIGHT)

    # ---------- 主题（零依赖：clam 主题 + 手工配色） ----------
    def apply_theme(name):
        """切换浅色/深色。ttk 走 clam 主题逐项配色，tk.Text 与经典滚动条单独设色。"""
        pal = PALETTES.get(name, PALETTES["light"])
        style = ttk.Style(root)
        try:
            style.theme_use("clam")  # vista/winnative 不允许自定义大部分颜色
        except tk.TclError:
            pass

        style.configure(
            ".", background=pal["bg"], foreground=pal["text"],
            fieldbackground=pal["field"], bordercolor=pal["border"],
            lightcolor=pal["bg"], darkcolor=pal["bg"], troughcolor=pal["field"],
            focuscolor=pal["select"],
        )
        style.configure("TFrame", background=pal["bg"])
        style.configure("TLabelframe", background=pal["bg"], bordercolor=pal["border"])
        style.configure("TLabelframe.Label", background=pal["bg"], foreground=pal["muted"])
        style.configure("TLabel", background=pal["bg"], foreground=pal["text"])
        style.configure(
            "TButton", background=pal["btn"], foreground=pal["text"],
            bordercolor=pal["border"], arrowcolor=pal["text"],
        )
        style.map(
            "TButton",
            background=[("active", pal["btn_active"]), ("disabled", pal["bg"])],
            foreground=[("disabled", pal["muted"])],
        )
        style.configure(
            "TCheckbutton", background=pal["bg"], foreground=pal["text"],
            indicatorcolor=pal["field"],
        )
        style.map("TCheckbutton", background=[("active", pal["bg"])])
        style.configure(
            "TEntry", fieldbackground=pal["field"], foreground=pal["text"],
            insertcolor=pal["text"], bordercolor=pal["border"],
        )
        style.configure(
            "TCombobox", fieldbackground=pal["field"], background=pal["btn"],
            foreground=pal["text"], arrowcolor=pal["text"],
            bordercolor=pal["border"],
        )
        style.map(
            "TCombobox",
            fieldbackground=[("readonly", pal["field"])],
            foreground=[("readonly", pal["text"])],
        )
        # 下拉列表是经典 Listbox，只能通过 option 数据库改色
        root.option_add("*TCombobox*Listbox.background", pal["field"])
        root.option_add("*TCombobox*Listbox.foreground", pal["text"])
        root.option_add("*TCombobox*Listbox.selectBackground", pal["select"])
        root.option_add("*TCombobox*Listbox.selectForeground", pal["text"])

        root.configure(bg=pal["bg"])
        for text_widget in (card_text, log_widget):
            text_widget.configure(
                bg=pal["field"], fg=pal["text"], insertbackground=pal["text"],
                selectbackground=pal["select"], highlightbackground=pal["border"],
            )
            # scrolledtext 自带的是经典 tk.Scrollbar（tk.Text 的兄弟控件）
            for sibling in text_widget.master.winfo_children():
                if sibling.winfo_class() == "Scrollbar":
                    sibling.configure(
                        bg=pal["btn"], troughcolor=pal["bg"],
                        activebackground=pal["btn_active"],
                        highlightbackground=pal["bg"],
                    )

        # 状态文本颜色随主题（文字本身由 set_running 控制）
        set_running(service.is_running)
        return pal

    def on_theme_toggle():
        nonlocal theme_name
        theme_name = "dark" if is_dark_var.get() else "light"
        apply_theme(theme_name)
        log("[界面] 已切换到%s模式" % ("深色" if theme_name == "dark" else "浅色"))
        try:
            ftp_core.save_config(
                user_var.get().strip(), pass_var.get(), _current_port(),
                dir_var.get().strip(), list(dir_box.cget("values")), theme_name,
            )
        except Exception:
            pass

    # ---------- 状态机 ----------
    def _current_port():
        try:
            return int(port_var.get().strip())
        except ValueError:
            return ftp_core.DEFAULT_PORT

    def set_running(running):
        def set_enabled(holders, enabled):
            """递归启用/禁用表单控件（holder 里还套了一层 Frame，只改直接子节点会漏）"""
            state = tk.NORMAL if enabled else tk.DISABLED
            stack = list(holders)
            while stack:
                widget = stack.pop()
                for child in widget.winfo_children():
                    stack.append(child)
                    try:
                        child.configure(state=state)
                    except tk.TclError:
                        pass

        if running:
            status_var.set("● 服务运行中")
            status_label.configure(foreground=PALETTES[theme_name]["ok"])
            start_button.configure(state=tk.DISABLED)
            stop_button.configure(state=tk.NORMAL)
            set_enabled((user_holder, pass_holder, port_holder, dir_holder), False)
        else:
            status_var.set("● 未启动")
            status_label.configure(foreground=PALETTES[theme_name]["err"])
            start_button.configure(state=tk.NORMAL)
            stop_button.configure(state=tk.DISABLED)
            set_enabled((user_holder, pass_holder, port_holder, dir_holder), True)
            # 密码框恢复掩码显示
            entry.configure(show="*")

    def remember_dir(path):
        try:
            history = [d for d in (dir_box.cget("values") or []) if d and d != path]
        except Exception:
            history = []
        history.insert(0, path)
        dir_box.configure(values=tuple(history[:10]))

    def start_service():
        user = user_var.get().strip()
        password = pass_var.get()
        path = dir_var.get().strip()
        port = _current_port()

        ok, msg = service.start(user, password, path, port)
        log("[服务] %s" % msg)
        if not ok:
            messagebox.showerror("无法启动", msg)
            return

        remember_dir(path)
        ftp_core.save_config(user, password, port, path, list(dir_box.cget("values")), theme_name)
        refresh_card()
        set_running(True)

        # 启动后自动回环自检（避免「看起来启动了但连不上」）
        def selftest():
            passed = ftp_core.run_selftest(user, password, port)
            log_queue.put("[自检] %s" % ("通过（写入/列出/删除均正常）" if passed else "失败，请检查防火墙或杀毒软件"))
            if not passed:
                log_queue.put("[自检] 手机端若连不上：确认同一局域网、放行 python/本程序 的入站规则")

        threading.Thread(target=selftest, daemon=True).start()

    def stop_service():
        service.stop()
        set_running(False)

    start_button.configure(command=start_service)
    stop_button.configure(command=stop_service)

    # ---------- 日志泵：服务线程 → 界面线程 ----------
    def pump_log_queue():
        drained = 0
        while drained < 200:
            try:
                item = log_queue.get_nowait()
            except queue.Empty:
                break
            drained += 1
            if isinstance(item, tuple) and item[0] == "CONN":
                count = item[1]
                extra = "（%d 个连接）" % count if service.is_running else ""
                status_var.set("● 服务运行中%s" % (extra if count else ""))
                continue
            log(item)
        root.after(150, pump_log_queue)

    def on_close():
        if service.is_running and not messagebox.askyesno(
            "退出", "FTP 服务正在运行，退出将停止服务。确定退出吗？"
        ):
            return
        service.stop()
        if not service.is_running:
            # 退出前保存当前界面上的配置（含目录历史）
            try:
                ftp_core.save_config(
                    user_var.get().strip(),
                    pass_var.get(),
                    _current_port(),
                    dir_var.get().strip(),
                    list(dir_box.cget("values")),
                    theme_name,
                )
            except Exception:
                pass
        root.destroy()

    root.protocol("WM_DELETE_WINDOW", on_close)

    # ---------- 初始状态 ----------
    if not ftp_core.dependency_ok():
        start_button.configure(state=tk.DISABLED)
        log("[依赖] 未安装 pyftpdlib，请执行:  pip install pyftpdlib  （exe 版已内置，无需安装）")
    if ftp_core.port_in_use(_current_port()):
        log("[提示] 端口 %d 已被占用，可能是其它 FTP 服务正在运行" % _current_port())
    refresh_card()
    pump_log_queue()
    theme_check.configure(command=on_theme_toggle)
    apply_theme(theme_name)

    def check_update_async():
        """后台检查配套 App 是否有新版本（exe 随 App release 发布）"""
        latest, newer = ftp_core.check_update()
        if newer:
            log_queue.put(
                "[更新] 配套 DataBackup 已更新到 %s（本工具构建基于 %s），"
                "最新配套工具请到项目 Releases 下载" % (latest, ftp_core.app_build_tag())
            )

    threading.Thread(target=check_update_async, daemon=True).start()

    if preset_user or preset_password or preset_dir:
        log("[界面] 已按命令行参数预填账号密码与目录")
    log("[界面] 填好账号密码与目录后点「开启」；手机端按上方卡片填写")

    root.mainloop()
    return 0


# ---------------------------------------------------------------------------

def main():
    attach_parent_console()

    raw = sys.argv[1:]
    flags = [a for a in raw if a.startswith("--")]
    positional = [a for a in raw if not a.startswith("--")]
    while len(positional) < 3:
        positional.append("")

    user = positional[0].strip()
    password = positional[1]
    backup_dir = positional[2].strip()

    if "--diagnose" in flags:
        diag_dir = ""
        for a in raw:
            if a.startswith("--backup-dir="):
                diag_dir = a.split("=", 1)[1].strip()
        sys.exit(headless_diagnose(diag_dir or backup_dir, ftp_core.DEFAULT_PORT))

    if "--exit-after-selftest" in flags:
        if not user:
            user = ftp_core.DEFAULT_USER
        if not password:
            password = ftp_core.gen_password()
        if not backup_dir:
            backup_dir = ftp_core.default_backup_dir()
        sys.exit(headless_selftest(user, password, backup_dir, ftp_core.DEFAULT_PORT))

    if not ftp_core.dependency_ok():
        # GUI 也要能打开（让用户看到明确提示），但缺依赖时 pip 提示更直接
        try:
            import tkinter  # noqa: F401
        except ImportError:
            out("缺少依赖: 请执行  pip install pyftpdlib")
            sys.exit(1)

    try:
        sys.exit(main_gui(user, password, backup_dir))
    except Exception as e:
        # GUI 起不来（无桌面环境等）时退回无界面自检，便于排查
        out("[错误] 图形界面启动失败: %s" % e)
        sys.exit(1)


if __name__ == "__main__":
    main()
